main: Stack.o LinkedList.o Tour.o Driver.o
	g++ Stack.o LinkedList.o Driver.o -o main

Tour.o: Tour.cpp Tour.h
	g++ -c Tour.cpp

Stack.o: Stack.cpp Stack.h
	g++ -c Stack.cpp 

LinkedList.o: LinkedList.cpp LinkedList.h
	g++ -c LinkedList.cpp 

Driver.o: Driver.cpp
	g++ -c Driver.cpp 
